version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: k6ai
      MYSQL_USER: k6user
      MYSQL_PASSWORD: k6password
    ports:
      - "3306:3306"
    command:
      - "--sort-buffer-size=16M"
      - "--max-allowed-packet=100M"
    mem_limit: "1g"
    cpus: 1.0

  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend/results:/app/results
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    mem_limit: "2g"
    cpus: 2.0

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    depends_on:
      - backend
    ports:
      - "80:3000"
    mem_limit: "512m"
    cpus: 0.5
